### ISSUE TITLE
Add 'DefaultFunc' for voms provider parameter 

### ISSUE THREAD

**Issue by dvianello** [enolfc/egi-openstack-terraform#1]
Hello! 

Thanks for this work - really useful! 

A small suggestion that I believe would go a long way: is it possible to define a `DefaultFunc` for the `voms` parameter in this provider (see [here](https://github.com/enolfc/egi-openstack-terraform/blob/1cc2c28cd3cf1e65f35d05d168b5963e0b2f8424/openstack/provider.go)) pointing to an arbitrary environment variable (say `OS_VOMS`)? 

This is the behaviour for all the other parameters in the provider and will allow defining the infrastructure to which we're deploying from environment variables avoiding to duplicate the provider declaration to support the FedCloud (as we would need to manually define `voms = true` on the fedcloud provider).

Thanks!
Dario

**Comment by enolfc** [comment]
Fix commited for v0.8.8, other versions still need work. 

Currently, rethinking how to handle the dependencies to make this easier to maintain
